#"Copyright (c) 2019-present Lenovo
#Licensed under BSD-3, see COPYING.BSD file for details."


- name: fan1_status
  path: /system/chassis/motherboard/FAN0_Status
  methods:
    - type: tach
      sensors:
        - fan1

- name: fan2_status
  path: /system/chassis/motherboard/FAN1_Status
  methods:
    - type: tach
      sensors:
        - fan2

- name: fan3_status
  path: /system/chassis/motherboard/FAN2_Status
  methods:
    - type: tach
      sensors:
        - fan3

- name: fan4_status
  path: /system/chassis/motherboard/FAN3_Status
  methods:
    - type: tach
      sensors:
        - fan4

- name: fan5_status
  path: /system/chassis/motherboard/FAN4_Status
  methods:
    - type: tach
      sensors:
        - fan5

- name: fan6_status
  path: /system/chassis/motherboard/FAN5_Status
  methods:
    - type: tach
      sensors:
        - fan6
