#"Copyright ? 2019-present Lenovo
#Licensed under BSD-3, see COPYING.BSD file for details."


0x01:
  sensorType: 0x01
  path: /xyz/openbmc_project/sensors/temperature/Ambient_Temp
  sensorReadingType: 0x01
  multiplierM: 1
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  scale: -3
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x02:
  sensorType: 0x01
  path: /xyz/openbmc_project/sensors/temperature/Outlet_Temp
  sensorReadingType: 0x01
  multiplierM: 1
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  scale: -3
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t



0x21:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P12V_AUX_1
  sensorReadingType: 0x01
  multiplierM: 63
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -3
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x22:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P5V_AUX
  sensorReadingType: 0x01
  multiplierM: 5
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -2
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t



0x23:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P3V3_AUX
  sensorReadingType: 0x01
  multiplierM: 25
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -3
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t



0x24:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P1V8_PCH_AUX
  sensorReadingType: 0x01
  multiplierM: 105
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -4
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x25:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/PVNN_PCH_AUX
  sensorReadingType: 0x01
  multiplierM: 105
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -4
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

 
0x26:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P1V05_PCH_AUX
  sensorReadingType: 0x01
  multiplierM: 70
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -4
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x27:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P1V2_AUX
  sensorReadingType: 0x01
  multiplierM: 1
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -2
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x28:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P1V15_BMC_AUX
  sensorReadingType: 0x01
  multiplierM: 1
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -2
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x2C:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/PVDDQ_CPU1
  sensorReadingType: 0x01
  multiplierM: 1
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -2
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x2A:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/PVCCIO_CPU1
  sensorReadingType: 0x01
  multiplierM: 1
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -2
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t
0x29:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P12V_AUX_2
  sensorReadingType: 0x01
  multiplierM: 63
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -3
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x2D:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P12V
  sensorReadingType: 0x01
  multiplierM: 63
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -3
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x2E:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P5V
  sensorReadingType: 0x01
  multiplierM: 5
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -2
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x2F:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P3V3
  sensorReadingType: 0x01
  multiplierM: 25
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -3
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t             

0x2B:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P12V_AUX_3
  sensorReadingType: 0x01
  multiplierM: 63
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -3
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t
            
0x30:
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P3V_BAT
  sensorReadingType: 0x01
  multiplierM: 248
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  scale: -3
  rExp: -4
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t
            
0x40:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN0_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t



0x41:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN1_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t


0x42:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN2_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t


0x43:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN3_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x44:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN4_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x45:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN5_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t

0x46:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN6_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t          
0x47:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN7_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t       

0x48:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN8_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t  
0x49:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN9_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t       
0x4A:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN10_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t    

0x4B:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN11_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t  

0x4C:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN12_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t        
0x4D:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/FAN13_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t    

0x4E:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/PDB_FAN0_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t   

0x4F:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/PDB_FAN1_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t              
            
0x50:
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/PDB_FAN2_Speed
  sensorReadingType: 0x01
  multiplierM: 115
  offsetB: 0
  bExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  rExp: 0
  mutability: Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0x0:
            type: int64_t  
            