#!/bin/sh

# Copyright (c) 2019-present Lenovo
# Licensed under BSD-3, see COPYING.BSD file for details.

CPLD_I2C_BUS=1
CPLD_I2D_ADDR=0x44
REG_VERSION=0x1
VER_LEN=1
MAJOR_OFFET=2
MINOR_OFFET=3
SUB1=0
SUB2=0

VERSION=$(i2cget -y $CPLD_I2C_BUS $CPLD_I2D_ADDR $REG_VERSION)
MAJOR_VER=${VERSION:$MAJOR_OFFET:$VER_LEN}
MINOR_VER=${VERSION:$MINOR_OFFET:$VER_LEN}

FULL_VERSION=$MAJOR_VER.$MINOR_VER.$SUB1.$SUB2

echo $FULL_VERSION > /run/cpld0.version
